### PR TITLE
Add tenseal introduction notebook

### LINKED ISSUE #21: [KR2] Explore Tenseal tool for HE
[TenSEAL](https://github.com/OpenMined/TenSEAL) is a library for doing homomorphic encryption operations on tensors, built on top of [Microsoft SEAL](https://github.com/Microsoft/SEAL). It provides ease of use through a Python API, while preserving efficiency by implementing most of its operations using C++.

As a part of KR2, we would like to explore this tool and create a Helloworld notebook for the same.
Acceptance Criteria -

- [ ] A jupyter notebook that uses TenSEAL and performs basic encryption schemes and operations

### PR DESCRIPTION
**Pull request by aakankshaduggal**
Resolves #21

### CODE REVIEW

**Review by suppathak — COMMENTED** [review]
As an introduction to TenSeal . /lgtm 
Thanks @aakankshaduggal  :)

**Comment by aakankshaduggal** [comment]
@erikerlandson, as suggested by you I have added the `%timeit` to calculate the time taken to perform the operations.

**Review by erikerlandson — APPROVED** [review]
This looks good!

**Pull request merged**
